export const SCREEN_NAME = {
  HOME_PAGE: 'HOME_SCREEN',
  PROFILE_PAGE: 'PROFILE_SCREEN',
  OPTION_PAGE: 'OPTION_SCREEN',
  LOGIN_PAGE: 'LOGIN_SCREEN',
  REGISTER_PAGE: 'REGISTER_SCREEN',
  Tabs: 'Tabs',
};
